name: imx6ul-eisd-kernel
version: 3.14.52
summary: Chipsee imx6ul-eisd kernel snap
description: This is a kernel snap for imx6ul-eisd built using snappy_imx6ul_eisd_defconfig which plus the minimal snappy config changes based on imx6ul_eisd_defconfig
type: kernel
architectures:
  - armhf
confinement: devmode
grade: stable
parts:
  kernel:
    plugin: kernel
    #source: .
    source: https://github.com/leavs/kernel-3.14.52.git
    source-branch: master
    source-type: git
    kdefconfig: [snappy_imx6ul_eisd_defconfig]
    kconfigs:
      - CONFIG_LOCALVERSION="-snappy_v3.14"
    kernel-image-target: zImage
    kernel-device-trees:
      - imx6ul-eisd
    build-packages: [bc, kmod, cpio, lzop]
